name: Update Sinny
on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Nome del file (es. index.html)'
        required: true
      file_content:
        description: 'Contenuto Base64'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create index and index2 files
        run: |
          # Creiamo il primo file
          printf "%s" "${{ fromJson(github.event.inputs.file_content).index_content }}" | base64 --decode > index.html
          # Creiamo il secondo file (senza sovrascrivere il primo)
          printf "%s" "${{ fromJson(github.event.inputs.file_content).index2_content }}" | base64 --decode > index2.html

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Aggiungiamo TUTTI i file nuovi o modificati
          git add index.html index2.html
          git commit -m "Update index and index2 separately" || exit 0
          git push

