name: Update Sinny
on:
  workflow_dispatch:
    inputs:
      index_content:
        description: 'Base64 di index.html'
        required: true
      index2_content:
        description: 'Base64 di index2.html'
        required: true

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create index.html
        run: |
          printf "%s" "${{ github.event.inputs.index_content }}" | base64 --decode > index.html

      - name: Create index2.html
        run: |
          printf "%s" "${{ github.event.inputs.index2_content }}" | base64 --decode > index2.html

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          # Il trucco è qui: "|| echo" evita che il processo fallisca se non c'è nulla da cambiare
          git commit -m "Update from Shortcut" || exit 0
          git push
